scrape_configs:
  - job_name: 'MovieAppMetrics'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: 'Movie App'